var annotated_dup =
[
    [ "Debug", null, [
      [ "TimeLog", "structDebug_1_1TimeLog.html", null ]
    ] ],
    [ "Texture", null, [
      [ "Formats", "structTexture_1_1Formats.html", null ]
    ] ],
    [ "ArmyUnit", "structArmyUnit.html", null ],
    [ "Camera", "structCamera.html", null ],
    [ "CameraComponent", "structCameraComponent.html", null ],
    [ "Component", "structComponent.html", null ],
    [ "ComponentID", "structComponentID.html", null ],
    [ "ComponentSystem", "structComponentSystem.html", null ],
    [ "Device", "structDevice.html", null ],
    [ "Entity", "structEntity.html", null ],
    [ "FileData", "structFileData.html", null ],
    [ "FileExplorer", "structFileExplorer.html", null ],
    [ "FrameDescriptor", "structFrameDescriptor.html", null ],
    [ "GameData", "structGameData.html", null ],
    [ "HealthComponent", "structHealthComponent.html", null ],
    [ "HeapStack", "structHeapStack.html", null ],
    [ "Indices", "structIndices.html", null ],
    [ "InstanceData", "structInstanceData.html", null ],
    [ "LightSources", "structLightSources.html", null ],
    [ "Line", "structLine.html", null ],
    [ "MeleeComponent", "structMeleeComponent.html", null ],
    [ "Message", "structMessage.html", null ],
    [ "MessageSystem", "structMessageSystem.html", null ],
    [ "Model", "structModel.html", null ],
    [ "ModelData", "structModelData.html", null ],
    [ "ObjectUBO", "structObjectUBO.html", null ],
    [ "optional", "structoptional.html", null ],
    [ "OstenEngine", "structOstenEngine.html", null ],
    [ "QuadTree", "structQuadTree.html", null ],
    [ "QueueFamilyIndices", "structQueueFamilyIndices.html", null ],
    [ "RenderAble", "structRenderAble.html", null ],
    [ "RenderComponent", "structRenderComponent.html", null ],
    [ "RenderData", "structRenderData.html", null ],
    [ "RenderPipeline", "structRenderPipeline.html", null ],
    [ "ShadowPass", "structShadowPass.html", null ],
    [ "SimpleColliderComp", "structSimpleColliderComp.html", null ],
    [ "SwapChain", "structSwapChain.html", null ],
    [ "SwapChainImages", "structSwapChainImages.html", null ],
    [ "SwapChainSupportDetails", "structSwapChainSupportDetails.html", null ],
    [ "System", "structSystem.html", null ],
    [ "TempComp", "structTempComp.html", null ],
    [ "Terrain", "structTerrain.html", null ],
    [ "TextureArray", "structTextureArray.html", null ],
    [ "TextureImage", "structTextureImage.html", null ],
    [ "TextureStorage", "structTextureStorage.html", null ],
    [ "Timer", "structTimer.html", null ],
    [ "Transform", "structTransform.html", null ],
    [ "TransformComponent", "structTransformComponent.html", null ],
    [ "UIData", "structUIData.html", null ],
    [ "Uint32Array", "structUint32Array.html", null ],
    [ "Vertex", "structVertex.html", null ],
    [ "VertexArray", "structVertexArray.html", null ],
    [ "VertexAttributes", "structVertexAttributes.html", null ],
    [ "ViewDescriptor", "structViewDescriptor.html", null ],
    [ "ViewMatrix", "structViewMatrix.html", null ],
    [ "WindowExtensions", "structWindowExtensions.html", null ]
];