#pragma once
#include "../common_includes.h"
#include <vulkan/vulkan_core.h>
#include "descriptors/descriptors.cpp"
#include <cassert>
#include "device/vulkan/device.cpp"
#include "texture/vulkan/texture.cpp"
#include "swap_chain/vulkan/swap_chain.cpp"
#include "render_data/vulkan/render_data.cpp"
#include "model_loader/model_loader.cpp"
#include "renderable.h"
#include "../engine/entity_manager/components.h"
